version: "3.9"
services:
  strapi:
    image: osama144/strapi:latest
    container_name: Strapi
    networks:
      - networks_strapi
    restart: on-failure:5
    ports:
      - 1337:1337
    environment:
      NODE_ENV: "development"

networks:
  networks_strapi:
    name: Strapi
    driver: bridge