name: 📬 - Webhook

on:
  push:
    paths:
      - 'release/**'
  workflow_dispatch:

jobs:
  webhook:
    name: 📌 - Webhook
    runs-on: ubuntu-latest
    
    steps:
      - name: Verify Login
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Release Version
        id: fetch-release-version
        run: |
          version=$(cat release/strapi-latest.txt)
          echo "VERSION=${version}" >> $GITHUB_ENV

      - uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: POST
          payload: '{"content": null,"embeds": [{"description": "**Repositorie [${{ github.repository }}](${{ github.repository_url }})**\nA new version of **`Strapi`** has been released: **${{ env.VERSION }}**","color": 47359}],"username": "GitHub","avatar_url": "https://cdn.discordapp.com/attachments/829254863586066502/1257104692937363557/favicon.png?ex=6683317a&is=6681dffa&hm=f7c9e17332acb207287bbf72012f7c1172c7dfe341b377fe2e5cf6e215d3bb6b&","attachments": []}'